---
# The playbook deploys the mediawiki with mysql db
- name: Media Wiki Database 
  hosts: tag_group_db
  become: yes 
  
# encrypted  variables vault file
  vars_files: 
    - vault.yml

# Install db server 
  roles:
    - mysqldb


- name: Media Wiki WebServer
  hosts: tag_group_web
  become: yes
 
# encrypted  variables vault file
  vars_files: 
    - vault.yml

# install webserver(s)
  roles:
    - web 
