---
- name: enable latest php package for compatibility in Amazon linux
  command: sudo amazon-linux-extras enable php7.4

- name: enable latest php package for compatibility
  shell: 'sudo yum clean metadata'

- name: Install required packages 
  yum:
    name: "{{ packages_web }}"

- name: check and httpd version
  command: php --version && httpd --version

- name: start webserver
  systemd: state=started name=httpd enabled=true

- name: Download MediaWiki Binary from the link provided
  get_url: 
     url: 'https://releases.wikimedia.org/mediawiki/1.35/mediawiki-1.35.2.tar.gz'
     dest: '/tmp/mediawiki-1.35.2.tar.gz'
     mode: 0644

- name: Download the Signature for mediawiki from the link provided
  get_url: 
     url: 'https://releases.wikimedia.org/mediawiki/1.35/mediawiki-1.35.2.tar.gz.sig'
     dest: '/tmp/mediawiki-1.35.2.tar.gz.sig'
     mode: 0644
  
- name: Verify Signature
  command: gpg --verify /tmp/mediawiki-1.35.2.tar.gz.sig /tmp/mediawiki-1.35.2.tar.gz
  ignore_errors: yes

- name: Extract /tmp/mediawiki-1.35.2.tar.gz  into /var/www
  unarchive:
    src: /tmp/mediawiki-1.35.2.tar.gz
    dest: /var/www
    remote_src: yes

- name: create a symlink for /var/www/mediawiki-1.35.2/ to /var/www/mediawiki
  file: 
   src: '/var/www/mediawiki-1.35.2/'
   dest: '/var/www/mediawiki'
   state: link

- name: Backup the httpd configuration
  copy:
    src: "/etc/httpd/conf/httpd.conf"
    dest: "/etc/httpd/conf/httpd.conf_original"
    backup: yes
    remote_src: true

- name: add mediawiki files
  template: 
    src: ../templates/httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf

- name: set permissions for apache
  command: chown -R apache:apache /var/www/mediawiki

- name: restart httpd service
  systemd: name=httpd state=restarted
